//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaghaEnterprises.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceLines = new HashSet<InvoiceLine>();
        }
    
        public long InvoiceID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string PO_No { get; set; }
        public string TransportationMode { get; set; }
        public string Veh_No { get; set; }
        public string LR_No { get; set; }
        public Nullable<System.DateTime> LR_Date { get; set; }
        public Nullable<System.DateTime> DateTimeSupply { get; set; }
        public string CustomerName { get; set; }
        public string GST_No { get; set; }
        public string PAN_No { get; set; }
        public string CompanyAddress { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<decimal> Total_Nos_Bag { get; set; }
        public Nullable<decimal> Total_Nos_Kg { get; set; }
        public Nullable<decimal> TotalAmountBeforeTax { get; set; }
        public Nullable<decimal> Total_CGST { get; set; }
        public Nullable<decimal> Total_SGST { get; set; }
        public Nullable<decimal> Total_IGST { get; set; }
        public Nullable<decimal> Total_GST { get; set; }
        public Nullable<decimal> TotalAmountAfterTax { get; set; }
        public Nullable<decimal> TotalAfterRoundOff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
    }
}
