//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnaghaEnterprises.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        public long InvoiceLineID { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Nos_Bag { get; set; }
        public string Uom { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TaxableValue { get; set; }
        public Nullable<decimal> CGST_Rate { get; set; }
        public Nullable<decimal> CGST_Amount { get; set; }
        public Nullable<decimal> SGST_Rate { get; set; }
        public Nullable<decimal> SGST_Amount { get; set; }
        public Nullable<decimal> IGST_Rate { get; set; }
        public Nullable<decimal> IGST_Amount { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
